
version: "3" 
networks: 
  kong-net: 
    driver: bridge
services: 
  kong: 
    depends_on: 
      - kong-migration
      - kong-database
    environment: 
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_PROXY_LISTEN_SSL: "0.0.0.0:8443"
    healthcheck: 
      interval: 5s
      retries: 15
      test: 
        - CMD
        - curl
        - "-f"
        - "http://kong:8001"
      timeout: 2s
    image: "kong:latest"
    networks: 
      - kong-net
    ports: 
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
    restart: always
  kong-database: 
    environment: 
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
    healthcheck: 
      interval: 5s
      retries: 5
      test: 
        - CMD
        - pg_isready
        - "-U"
        - kong
      timeout: 5s
    image: "postgres:9.6"
    networks: 
      - kong-net
    ports: 
      - "5432:5432"
    restart: always
    volumes: 
      - "/opt/kong/kong-database:/var/lib/postgresql/data"
  kong-migration: 
    command: "kong migrations bootstrap"
    depends_on: 
      - kong-database
    environment: 
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    image: "kong:latest"
    links: 
      - kong-database
    networks: 
      - kong-net
    restart: on-failure
  konga: 
    depends_on: 
      - kong-database
    environment: 
      DB_ADAPTER: postgres
      DB_DATABASE: kong
      DB_HOST: kong-database
      DB_PASSWORD: kong
      DB_USER: kong
      NODE_ENV: production
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
    image: "pantsel/konga:latest"
    networks: 
      - kong-net
    ports: 
      - "1337:1337"
  konga-prepare: 
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/kong"
    depends_on: 
      - kong-database
    image: "pantsel/konga:next"
    links: 
      - kong-database
    networks: 
      - kong-net
    restart: on-failure
